base_url: "https://starkware.crowdin.com"
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  - source: /_crowdin/source/categories/*
    translation: /_crowdin/translation/%two_letters_code%/categories/%original_file_name%

  - source: /_crowdin/source/events/*
    translation: /_crowdin/translation/%two_letters_code%/events/%original_file_name%

  - source: /_crowdin/source/jobs/*
    translation: /_crowdin/translation/%two_letters_code%/jobs/%original_file_name%

  - source: /_crowdin/source/pages/*
    translation: /_crowdin/translation/%two_letters_code%/pages/%original_file_name%

  - source: /_crowdin/source/posts/*
    translation: /_crowdin/translation/%two_letters_code%/posts/%original_file_name%

  - source: /_crowdin/source/settings/*
    translation: /_crowdin/translation/%two_letters_code%/settings/%original_file_name%

  - source: /_crowdin/source/topics/*
    translation: /_crowdin/translation/%two_letters_code%/topics/%original_file_name%

  - source: /_crowdin/source/tutorials/*
    translation: /_crowdin/translation/%two_letters_code%/tutorials/%original_file_name%

  - source: /_crowdin/source/roadmap-posts/*
    translation: /_crowdin/translation/%two_letters_code%/roadmap-posts/%original_file_name%

  - source: /_crowdin/source/roadmap-versions/*
    translation: /_crowdin/translation/%two_letters_code%/roadmap-versions/%original_file_name%

  - source: /_crowdin/source/seo/*
    translation: /_crowdin/translation/%two_letters_code%/seo/%original_file_name%

  - source: /_crowdin/source/announcements/*
    translation: /_crowdin/translation/%two_letters_code%/announcements/%original_file_name%