id: e6336705-4eae-4c16-b26e-0664115b0f98
title: "Product update: April 2023"
description: Aliquet nec orci mattis amet quisque ullamcorper neque, nibh sem.
  At arcu, sit dui mi, nibh dui, diam eget.
image: /assets/10_-first-steps-to-contribute-to-kakarot-zkevm.png
badge: building-now
blocks:
  - type: markdown
    body: Aliquet nec orci mattis amet quisque ullamcorper neque, nibh sem. At arcu,
      sit dui mi, nibh dui, diam eget.
